---
version: '3'

includes:
  # ドキュメント関連タスク
  #
  # NOTE: この記述があるため、task実行時にはリモートファイル用の環境変数を宣言する必要があります。
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.2'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: ''
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - task: 'setup-ci'
      - 'nimble install -d'
      - 'lefthook install'
  setup-ci:
    desc: 'Setup for CI'
    cmds:
      - 'uv sync --frozen'
      - 'bun install'
